name: Lint and Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]
          pip install setuptools wheel twine

      - name: Lint
        run: make lintgit

      - name: Test
        run: make test

      - name: Build
        run: make build
