name: Lint and Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: make build
