name: Release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]
          pip install setuptools wheel twine
          pip install bump2version

      - name: Bump version
        run: bump2version minor

      - name: Build
        run: make build

      - name: Push changes
        run: |
          git push origin HEAD:main
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
